#ifndef SYCAMORE_DEFINES_H
#define SYCAMORE_DEFINES_H

#define NAMESPACE_SYCAMORE_BEGIN namespace sycamore {
#define NAMESPACE_SYCAMORE_END }

#define WLR_COMPOSITOR_VERSION 6
#define LAYER_SHELL_VERSION    4
#define XDG_SHELL_VERSION      3
#define LAYER_SHELL_LAYER_NUM  4
#define INPUT_DEVICE_TYPE_NUM  6

#endif //SYCAMORE_DEFINES_H